version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    # You can also specify other tool versions:
    # nodejs: "16"
  jobs:
    pre_install:
      - git update-index --assume-unchanged kfinance/version.py docs/conf.py

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
